// Generated by gencpp from file dynamixel_sdk_examples/SyncGetPositionResponse.msg
// DO NOT EDIT!


#ifndef DYNAMIXEL_SDK_EXAMPLES_MESSAGE_SYNCGETPOSITIONRESPONSE_H
#define DYNAMIXEL_SDK_EXAMPLES_MESSAGE_SYNCGETPOSITIONRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace dynamixel_sdk_examples
{
template <class ContainerAllocator>
struct SyncGetPositionResponse_
{
  typedef SyncGetPositionResponse_<ContainerAllocator> Type;

  SyncGetPositionResponse_()
    : position1(0)
    , position2(0)
    , position3(0)
    , position4(0)
    , position5(0)
    , position6(0)
    , position7(0)
    , position8(0)
    , position9(0)
    , position10(0)
    , position11(0)
    , position12(0)  {
    }
  SyncGetPositionResponse_(const ContainerAllocator& _alloc)
    : position1(0)
    , position2(0)
    , position3(0)
    , position4(0)
    , position5(0)
    , position6(0)
    , position7(0)
    , position8(0)
    , position9(0)
    , position10(0)
    , position11(0)
    , position12(0)  {
  (void)_alloc;
    }



   typedef int32_t _position1_type;
  _position1_type position1;

   typedef int32_t _position2_type;
  _position2_type position2;

   typedef int32_t _position3_type;
  _position3_type position3;

   typedef int32_t _position4_type;
  _position4_type position4;

   typedef int32_t _position5_type;
  _position5_type position5;

   typedef int32_t _position6_type;
  _position6_type position6;

   typedef int32_t _position7_type;
  _position7_type position7;

   typedef int32_t _position8_type;
  _position8_type position8;

   typedef int32_t _position9_type;
  _position9_type position9;

   typedef int32_t _position10_type;
  _position10_type position10;

   typedef int32_t _position11_type;
  _position11_type position11;

   typedef int32_t _position12_type;
  _position12_type position12;





  typedef boost::shared_ptr< ::dynamixel_sdk_examples::SyncGetPositionResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dynamixel_sdk_examples::SyncGetPositionResponse_<ContainerAllocator> const> ConstPtr;

}; // struct SyncGetPositionResponse_

typedef ::dynamixel_sdk_examples::SyncGetPositionResponse_<std::allocator<void> > SyncGetPositionResponse;

typedef boost::shared_ptr< ::dynamixel_sdk_examples::SyncGetPositionResponse > SyncGetPositionResponsePtr;
typedef boost::shared_ptr< ::dynamixel_sdk_examples::SyncGetPositionResponse const> SyncGetPositionResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dynamixel_sdk_examples::SyncGetPositionResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dynamixel_sdk_examples::SyncGetPositionResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::dynamixel_sdk_examples::SyncGetPositionResponse_<ContainerAllocator1> & lhs, const ::dynamixel_sdk_examples::SyncGetPositionResponse_<ContainerAllocator2> & rhs)
{
  return lhs.position1 == rhs.position1 &&
    lhs.position2 == rhs.position2 &&
    lhs.position3 == rhs.position3 &&
    lhs.position4 == rhs.position4 &&
    lhs.position5 == rhs.position5 &&
    lhs.position6 == rhs.position6 &&
    lhs.position7 == rhs.position7 &&
    lhs.position8 == rhs.position8 &&
    lhs.position9 == rhs.position9 &&
    lhs.position10 == rhs.position10 &&
    lhs.position11 == rhs.position11 &&
    lhs.position12 == rhs.position12;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::dynamixel_sdk_examples::SyncGetPositionResponse_<ContainerAllocator1> & lhs, const ::dynamixel_sdk_examples::SyncGetPositionResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace dynamixel_sdk_examples

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::dynamixel_sdk_examples::SyncGetPositionResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dynamixel_sdk_examples::SyncGetPositionResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dynamixel_sdk_examples::SyncGetPositionResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dynamixel_sdk_examples::SyncGetPositionResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dynamixel_sdk_examples::SyncGetPositionResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dynamixel_sdk_examples::SyncGetPositionResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dynamixel_sdk_examples::SyncGetPositionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ad0ef5485fbe76b84853e58fef60a126";
  }

  static const char* value(const ::dynamixel_sdk_examples::SyncGetPositionResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xad0ef5485fbe76b8ULL;
  static const uint64_t static_value2 = 0x4853e58fef60a126ULL;
};

template<class ContainerAllocator>
struct DataType< ::dynamixel_sdk_examples::SyncGetPositionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dynamixel_sdk_examples/SyncGetPositionResponse";
  }

  static const char* value(const ::dynamixel_sdk_examples::SyncGetPositionResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dynamixel_sdk_examples::SyncGetPositionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 position1\n"
"int32 position2\n"
"int32 position3\n"
"int32 position4\n"
"int32 position5\n"
"int32 position6\n"
"int32 position7\n"
"int32 position8\n"
"int32 position9\n"
"int32 position10\n"
"int32 position11\n"
"int32 position12\n"
"\n"
;
  }

  static const char* value(const ::dynamixel_sdk_examples::SyncGetPositionResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dynamixel_sdk_examples::SyncGetPositionResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.position1);
      stream.next(m.position2);
      stream.next(m.position3);
      stream.next(m.position4);
      stream.next(m.position5);
      stream.next(m.position6);
      stream.next(m.position7);
      stream.next(m.position8);
      stream.next(m.position9);
      stream.next(m.position10);
      stream.next(m.position11);
      stream.next(m.position12);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SyncGetPositionResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dynamixel_sdk_examples::SyncGetPositionResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dynamixel_sdk_examples::SyncGetPositionResponse_<ContainerAllocator>& v)
  {
    s << indent << "position1: ";
    Printer<int32_t>::stream(s, indent + "  ", v.position1);
    s << indent << "position2: ";
    Printer<int32_t>::stream(s, indent + "  ", v.position2);
    s << indent << "position3: ";
    Printer<int32_t>::stream(s, indent + "  ", v.position3);
    s << indent << "position4: ";
    Printer<int32_t>::stream(s, indent + "  ", v.position4);
    s << indent << "position5: ";
    Printer<int32_t>::stream(s, indent + "  ", v.position5);
    s << indent << "position6: ";
    Printer<int32_t>::stream(s, indent + "  ", v.position6);
    s << indent << "position7: ";
    Printer<int32_t>::stream(s, indent + "  ", v.position7);
    s << indent << "position8: ";
    Printer<int32_t>::stream(s, indent + "  ", v.position8);
    s << indent << "position9: ";
    Printer<int32_t>::stream(s, indent + "  ", v.position9);
    s << indent << "position10: ";
    Printer<int32_t>::stream(s, indent + "  ", v.position10);
    s << indent << "position11: ";
    Printer<int32_t>::stream(s, indent + "  ", v.position11);
    s << indent << "position12: ";
    Printer<int32_t>::stream(s, indent + "  ", v.position12);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DYNAMIXEL_SDK_EXAMPLES_MESSAGE_SYNCGETPOSITIONRESPONSE_H
