(cl:in-package dynamixel_sdk_examples-srv)
(cl:export '(ID1-VAL
          ID1
          ID2-VAL
          ID2
          ID3-VAL
          ID3
          ID4-VAL
          ID4
          ID5-VAL
          ID5
          ID6-VAL
          ID6
          ID7-VAL
          ID7
          ID8-VAL
          ID8
          ID9-VAL
          ID9
          ID10-VAL
          ID10
          ID11-VAL
          ID11
          ID12-VAL
          ID12
          POSITION1-VAL
          POSITION1
          POSITION2-VAL
          POSITION2
          POSITION3-VAL
          POSITION3
          POSITION4-VAL
          POSITION4
          POSITION5-VAL
          POSITION5
          POSITION6-VAL
          POSITION6
          POSITION7-VAL
          POSITION7
          POSITION8-VAL
          POSITION8
          POSITION9-VAL
          POSITION9
          POSITION10-VAL
          POSITION10
          POSITION11-VAL
          POSITION11
          POSITION12-VAL
          POSITION12
))